on:
  - push

jobs:
  test_action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ./
        id: test
      - run: echo "${{ steps.test.outputs.matrix }}"